CREATE CONSTRAINT IF NOT EXISTS FOR (node:Projection) REQUIRE node.id IS UNIQUE;

CREATE CONSTRAINT IF NOT EXISTS FOR (node:PostAggregate) REQUIRE node.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (node:Post) REQUIRE node.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (node:Comment) REQUIRE node.id IS UNIQUE;
