name: Test

on:
  push:
    branches:
      - main
#      - features/**
#      - dependabot/**
  pull_request:
    branches:
      - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 Corretto for sake of test/build
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build java code with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Start containers
        run: docker-compose -f "app-stripped-docker-compose.yaml" up -d --build



# From here, the app can be started either within docker or outside. Possibly tested against HTTPs with curl, node or other relevant test framework
# Following code for running possible node tests:

#      - name: Install node
#        uses: actions/setup-node@v1
#        with:
#          node-version: 14.x
#      - name: Install dependencies
#        run: npm install
#      - name: Run tests
#        run: npm run test

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yaml" down